version: '3.8'

services:

  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: gateway
    networks:
      - learning-network
    depends_on:
      - users-service
      - master-service
      - postgres

  users-service:
    build: 
      context: ../users-service
      dockerfile: Dockerfile
    container_name: users-service
    networks:
      - learning-network
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    volumes:
      - ./users-service:/app

  # master-service:
  #   build: 
  #     context: ../master-service
  #     dockerfile: Dockerfile
  #   container_name: master-service
  #   networks:
  #     - learning-network
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./master-service:/app

  # activities-service:
  #   build: 
  #     context: ../activities-service
  #     dockerfile: Dockerfile
  #   container_name: activities-service
  #   networks:
  #     - learning-network
  #   ports:
  #     - "8083:8083"
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./activities-service:/app

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: learningdb
    container_name: postgres
    networks:
      - learning-network
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


networks:
  learning-network:
    driver: bridge
