name: learning-go

services:

  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    ports:
      - "${GATEWAY_PORT:-80}:80"
    container_name: gateway-learninggo
    networks:
      - learning-network
    depends_on:
      - users-service
      # - master-service
      # - activities-service
    environment:
      - USERS_SERVICE_HOST=users-service
      - USERS_SERVICE_GRPC_PORT=${USERS_SERVICE_GRPC_PORT:-50051}
      - USERS_SERVICE_REST_PORT=${USERS_SERVICE_REST_PORT:-4001}
      - MASTER_SERVICE_HOST=master-service
      - MASTER_SERVICE_GRPC_PORT=${MASTER_SERVICE_GRPC_PORT:-50052}
      - MASTER_SERVICE_REST_PORT=${MASTER_SERVICE_REST_PORT:-4002}
      
      - ACTIVITIES_SERVICE_HOST=activities-service
      - ACTIVITIES_SERVICE_PORT=${ACTIVITIES_SERVICE_PORT:-50053}

  users-service:
    build: 
      context: ../
      dockerfile: users-service/Dockerfile.dev
    container_name: users-service-learninggo
    networks:
      - learning-network
    ports:
      - "${USERS_SERVICE_GRPC_PORT:-50051}:${USERS_SERVICE_GRPC_PORT:-50051}"
      - "${USERS_SERVICE_REST_PORT:-4001}:${USERS_SERVICE_REST_PORT:-4001}"
    depends_on:
      - postgres
    volumes:
      - ./../users-service:/app
    environment:
      - POSTGRES_HOST=postgres


  # master-service:
  #   build: 
  #     context: ../master-service
  #     dockerfile: Dockerfile
  #   container_name: master-service
  #   networks:
  #     - learning-network
  # ports:
  #   - "${MASTER_SERVICE_GRPC_PORT:-50052}:${MASTER_SERVICE_GRPC_PORT:-50052}"
  #   - "${MASTER_SERVICE_REST_PORT:-4002}:${MASTER_SERVICE_REST_PORT:-4002}"
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./master-service:/app
  #   environment:
  #     - POSTGRES_HOST=postgres

  # activities-service:
  #   build: 
  #     context: ../activities-service
  #     dockerfile: Dockerfile
  #   container_name: activities-service
  #   networks:
  #     - learning-network
  # ports:
  #   - "${ACTIVITIES_SERVICE_GRPC_PORT:-50053}:${ACTIVITIES_SERVICE_GRPC_PORT:-50053}"
  #   - "${ACTIVITIES_SERVICE_REST_PORT:-4003}:${ACTIVITIES_SERVICE_REST_PORT:-4003}"
  #   environment:
  #     - POSTGRES_HOST=postgres
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./activities-service:/app

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-learningdb}
    container_name: postgres-learninggo
    networks:
      - learning-network
    ports:
      - "${POSTGRES_PORT:-5440}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


networks:
  learning-network:
    driver: bridge
