name: learning-go-test

services:

  load-balancer-learninggo:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: load-balancer-learninggo-test
    volumes:
      - ../gateway/nginx-test.conf:/etc/nginx/nginx.conf # Use test NGINX config
    ports:
      - "50071:50051" # Expose gRPC port
      - "4071:4001"   # Expose HTTP REST port
    networks:
      - learning-test-network
    depends_on:
      - service

  service:
    build: 
      context: ../service
      dockerfile: Dockerfile.test
    networks:
      - learning-test-network
    ports:
      - "50051"
      - "4001"
    container_name: service-test
  
  postgres:
    image: postgres:13-alpine
    container_name: postgres-learninggo-test
    environment:
      POSTGRES_USER: ${POSTGRES_USER_TEST:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST:-secret}
      POSTGRES_DB: ${POSTGRES_DB_TEST:-learningdb}
    networks:
      - learning-test-network
    ports:
      - "5433:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    container_name: redis-learninggo-test
    networks:
      - learning-test-network
    ports:
      - "6380:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD_TEST}"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD_TEST} # Use test Redis password

volumes:
  postgres-test-data:

networks:
  learning-test-network:
    driver: bridge