name: learning-go-test

services:

  load-balancer-learninggo-test:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    volumes:
      - ./nginx-test.conf:/etc/nginx/nginx.conf # Use test NGINX config
    ports:
      - "50071:50051" # Expose gRPC port
      - "4071:4001"   # Expose HTTP REST port
    networks:
      - learning-network
    depends_on:
      - service-test

  service-test:
    build: 
      context: ../service
      dockerfile: Dockerfile
    networks:
      - learning-network
    depends_on:
      - postgres-test
    ports:
      - "50051"
      - "4001"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TEST} # Use test DB
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      GATEWAY_PORT: ${GATEWAY_PORT}
      SERVICE_GRPC_PORT: ${SERVICE_GRPC_PORT}
      SERVICE_REST_PORT: ${SERVICE_REST_PORT}
      MASTER_SERVICE_GRPC_PORT: ${MASTER_SERVICE_GRPC_PORT}
      MASTER_SERVICE_REST_PORT: ${MASTER_SERVICE_REST_PORT}
      ACTIVITIES_SERVICE_GRPC_PORT: ${ACTIVITIES_SERVICE_GRPC_PORT}
      ACTIVITIES_SERVICE_REST_PORT: ${ACTIVITIES_SERVICE_REST_PORT}
      JWT_SECRET: ${JWT_SECRET}

  postgres-test:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB_TEST:-learningdb-test} # Use test DB
    container_name: postgres-test-learninggo # Different container name
    networks:
      - learning-network
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

networks:
  learning-network:
    driver: bridge